import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect, createRef } from 'react'
import Lottie from 'lottie-web'

import Carousel from '../components/Carousel'
import SplashScreen from '../components/SplashScreen'
import BackgroundMusic from '../components/BackgroundMusic'


export default function Home() {

  return (
    <>
      <Head>
        <title>BeeBoo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Carousel />
        <BackgroundMusic />
      </main>
    </>
  )
}
